Dear {X_UNAME},

"{X_FROMUNAME}" shows interest in your {X_SITENAME} profile! 

Click on the following link to view, reply or delete this interest message :
{X_ITEM_URL}

To view the profile of "{X_FROMUNAME}" click on the following link {X_VIEW_MEMBER}


-----------

Please do not reply to this message.

{X_SITENAME} ({X_SITEURL}) 

-----------
This interest is generated by the MyLatinSoulmate Friends module - visit http://www.mylatinsoulmate.com